name: gochat_client
description: A cross-platform chat application built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & WebSocket
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Image & File
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  file_picker: ^6.1.1
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.3.3
  
  # Window Management
  window_manager: ^0.3.7
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - images/
  
  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
