// Code generated by ent, DO NOT EDIT.

package groupchatrecord

import (
	"gochat_server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldID, id))
}

// MsgId applies equality check predicate on the "msgId" field. It's identical to MsgIdEQ.
func MsgId(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldMsgId, v))
}

// FromUserId applies equality check predicate on the "fromUserId" field. It's identical to FromUserIdEQ.
func FromUserId(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldFromUserId, v))
}

// GroupId applies equality check predicate on the "groupId" field. It's identical to GroupIdEQ.
func GroupId(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldGroupId, v))
}

// MsgType applies equality check predicate on the "msgType" field. It's identical to MsgTypeEQ.
func MsgType(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldMsgType, v))
}

// CreateTime applies equality check predicate on the "createTime" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldCreateTime, v))
}

// MsgIdEQ applies the EQ predicate on the "msgId" field.
func MsgIdEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldMsgId, v))
}

// MsgIdNEQ applies the NEQ predicate on the "msgId" field.
func MsgIdNEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldMsgId, v))
}

// MsgIdIn applies the In predicate on the "msgId" field.
func MsgIdIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldMsgId, vs...))
}

// MsgIdNotIn applies the NotIn predicate on the "msgId" field.
func MsgIdNotIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldMsgId, vs...))
}

// MsgIdGT applies the GT predicate on the "msgId" field.
func MsgIdGT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldMsgId, v))
}

// MsgIdGTE applies the GTE predicate on the "msgId" field.
func MsgIdGTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldMsgId, v))
}

// MsgIdLT applies the LT predicate on the "msgId" field.
func MsgIdLT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldMsgId, v))
}

// MsgIdLTE applies the LTE predicate on the "msgId" field.
func MsgIdLTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldMsgId, v))
}

// MsgIdContains applies the Contains predicate on the "msgId" field.
func MsgIdContains(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContains(FieldMsgId, v))
}

// MsgIdHasPrefix applies the HasPrefix predicate on the "msgId" field.
func MsgIdHasPrefix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasPrefix(FieldMsgId, v))
}

// MsgIdHasSuffix applies the HasSuffix predicate on the "msgId" field.
func MsgIdHasSuffix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasSuffix(FieldMsgId, v))
}

// MsgIdEqualFold applies the EqualFold predicate on the "msgId" field.
func MsgIdEqualFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEqualFold(FieldMsgId, v))
}

// MsgIdContainsFold applies the ContainsFold predicate on the "msgId" field.
func MsgIdContainsFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContainsFold(FieldMsgId, v))
}

// FromUserIdEQ applies the EQ predicate on the "fromUserId" field.
func FromUserIdEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldFromUserId, v))
}

// FromUserIdNEQ applies the NEQ predicate on the "fromUserId" field.
func FromUserIdNEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldFromUserId, v))
}

// FromUserIdIn applies the In predicate on the "fromUserId" field.
func FromUserIdIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldFromUserId, vs...))
}

// FromUserIdNotIn applies the NotIn predicate on the "fromUserId" field.
func FromUserIdNotIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldFromUserId, vs...))
}

// FromUserIdGT applies the GT predicate on the "fromUserId" field.
func FromUserIdGT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldFromUserId, v))
}

// FromUserIdGTE applies the GTE predicate on the "fromUserId" field.
func FromUserIdGTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldFromUserId, v))
}

// FromUserIdLT applies the LT predicate on the "fromUserId" field.
func FromUserIdLT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldFromUserId, v))
}

// FromUserIdLTE applies the LTE predicate on the "fromUserId" field.
func FromUserIdLTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldFromUserId, v))
}

// FromUserIdContains applies the Contains predicate on the "fromUserId" field.
func FromUserIdContains(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContains(FieldFromUserId, v))
}

// FromUserIdHasPrefix applies the HasPrefix predicate on the "fromUserId" field.
func FromUserIdHasPrefix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasPrefix(FieldFromUserId, v))
}

// FromUserIdHasSuffix applies the HasSuffix predicate on the "fromUserId" field.
func FromUserIdHasSuffix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasSuffix(FieldFromUserId, v))
}

// FromUserIdEqualFold applies the EqualFold predicate on the "fromUserId" field.
func FromUserIdEqualFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEqualFold(FieldFromUserId, v))
}

// FromUserIdContainsFold applies the ContainsFold predicate on the "fromUserId" field.
func FromUserIdContainsFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContainsFold(FieldFromUserId, v))
}

// GroupIdEQ applies the EQ predicate on the "groupId" field.
func GroupIdEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldGroupId, v))
}

// GroupIdNEQ applies the NEQ predicate on the "groupId" field.
func GroupIdNEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldGroupId, v))
}

// GroupIdIn applies the In predicate on the "groupId" field.
func GroupIdIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldGroupId, vs...))
}

// GroupIdNotIn applies the NotIn predicate on the "groupId" field.
func GroupIdNotIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldGroupId, vs...))
}

// GroupIdGT applies the GT predicate on the "groupId" field.
func GroupIdGT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldGroupId, v))
}

// GroupIdGTE applies the GTE predicate on the "groupId" field.
func GroupIdGTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldGroupId, v))
}

// GroupIdLT applies the LT predicate on the "groupId" field.
func GroupIdLT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldGroupId, v))
}

// GroupIdLTE applies the LTE predicate on the "groupId" field.
func GroupIdLTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldGroupId, v))
}

// GroupIdContains applies the Contains predicate on the "groupId" field.
func GroupIdContains(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContains(FieldGroupId, v))
}

// GroupIdHasPrefix applies the HasPrefix predicate on the "groupId" field.
func GroupIdHasPrefix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasPrefix(FieldGroupId, v))
}

// GroupIdHasSuffix applies the HasSuffix predicate on the "groupId" field.
func GroupIdHasSuffix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasSuffix(FieldGroupId, v))
}

// GroupIdEqualFold applies the EqualFold predicate on the "groupId" field.
func GroupIdEqualFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEqualFold(FieldGroupId, v))
}

// GroupIdContainsFold applies the ContainsFold predicate on the "groupId" field.
func GroupIdContainsFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContainsFold(FieldGroupId, v))
}

// MsgTypeEQ applies the EQ predicate on the "msgType" field.
func MsgTypeEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldMsgType, v))
}

// MsgTypeNEQ applies the NEQ predicate on the "msgType" field.
func MsgTypeNEQ(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldMsgType, v))
}

// MsgTypeIn applies the In predicate on the "msgType" field.
func MsgTypeIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldMsgType, vs...))
}

// MsgTypeNotIn applies the NotIn predicate on the "msgType" field.
func MsgTypeNotIn(vs ...string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldMsgType, vs...))
}

// MsgTypeGT applies the GT predicate on the "msgType" field.
func MsgTypeGT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldMsgType, v))
}

// MsgTypeGTE applies the GTE predicate on the "msgType" field.
func MsgTypeGTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldMsgType, v))
}

// MsgTypeLT applies the LT predicate on the "msgType" field.
func MsgTypeLT(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldMsgType, v))
}

// MsgTypeLTE applies the LTE predicate on the "msgType" field.
func MsgTypeLTE(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldMsgType, v))
}

// MsgTypeContains applies the Contains predicate on the "msgType" field.
func MsgTypeContains(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContains(FieldMsgType, v))
}

// MsgTypeHasPrefix applies the HasPrefix predicate on the "msgType" field.
func MsgTypeHasPrefix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasPrefix(FieldMsgType, v))
}

// MsgTypeHasSuffix applies the HasSuffix predicate on the "msgType" field.
func MsgTypeHasSuffix(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldHasSuffix(FieldMsgType, v))
}

// MsgTypeEqualFold applies the EqualFold predicate on the "msgType" field.
func MsgTypeEqualFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEqualFold(FieldMsgType, v))
}

// MsgTypeContainsFold applies the ContainsFold predicate on the "msgType" field.
func MsgTypeContainsFold(v string) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldContainsFold(FieldMsgType, v))
}

// CreateTimeEQ applies the EQ predicate on the "createTime" field.
func CreateTimeEQ(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "createTime" field.
func CreateTimeNEQ(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "createTime" field.
func CreateTimeIn(vs ...time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "createTime" field.
func CreateTimeNotIn(vs ...time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "createTime" field.
func CreateTimeGT(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "createTime" field.
func CreateTimeGTE(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "createTime" field.
func CreateTimeLT(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "createTime" field.
func CreateTimeLTE(v time.Time) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.FieldLTE(FieldCreateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupChatRecord) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupChatRecord) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupChatRecord) predicate.GroupChatRecord {
	return predicate.GroupChatRecord(sql.NotPredicates(p))
}
