// Code generated by ent, DO NOT EDIT.

package videomessage

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the videomessage type in the database.
	Label = "video_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMsgId holds the string denoting the msgid field in the database.
	FieldMsgId = "msg_id"
	// FieldVideoUrl holds the string denoting the videourl field in the database.
	FieldVideoUrl = "video_url"
	// Table holds the table name of the videomessage in the database.
	Table = "video_messages"
)

// Columns holds all SQL columns for videomessage fields.
var Columns = []string{
	FieldID,
	FieldMsgId,
	FieldVideoUrl,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	MsgIdValidator func(string) error
	// VideoUrlValidator is a validator for the "videoUrl" field. It is called by the builders before save.
	VideoUrlValidator func(string) error
)

// OrderOption defines the ordering options for the VideoMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMsgId orders the results by the msgId field.
func ByMsgId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMsgId, opts...).ToFunc()
}

// ByVideoUrl orders the results by the videoUrl field.
func ByVideoUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoUrl, opts...).ToFunc()
}
