// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gochat_server/ent/chatrecord"
	"gochat_server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRecordDelete is the builder for deleting a ChatRecord entity.
type ChatRecordDelete struct {
	config
	hooks    []Hook
	mutation *ChatRecordMutation
}

// Where appends a list predicates to the ChatRecordDelete builder.
func (crd *ChatRecordDelete) Where(ps ...predicate.ChatRecord) *ChatRecordDelete {
	crd.mutation.Where(ps...)
	return crd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crd *ChatRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, crd.sqlExec, crd.mutation, crd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (crd *ChatRecordDelete) ExecX(ctx context.Context) int {
	n, err := crd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crd *ChatRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chatrecord.Table, sqlgraph.NewFieldSpec(chatrecord.FieldID, field.TypeInt))
	if ps := crd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, crd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	crd.mutation.done = true
	return affected, err
}

// ChatRecordDeleteOne is the builder for deleting a single ChatRecord entity.
type ChatRecordDeleteOne struct {
	crd *ChatRecordDelete
}

// Where appends a list predicates to the ChatRecordDelete builder.
func (crdo *ChatRecordDeleteOne) Where(ps ...predicate.ChatRecord) *ChatRecordDeleteOne {
	crdo.crd.mutation.Where(ps...)
	return crdo
}

// Exec executes the deletion query.
func (crdo *ChatRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := crdo.crd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chatrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crdo *ChatRecordDeleteOne) ExecX(ctx context.Context) {
	if err := crdo.Exec(ctx); err != nil {
		panic(err)
	}
}
