// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gochat_server/ent/chatrecord"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRecordCreate is the builder for creating a ChatRecord entity.
type ChatRecordCreate struct {
	config
	mutation *ChatRecordMutation
	hooks    []Hook
}

// SetMsgId sets the "msgId" field.
func (crc *ChatRecordCreate) SetMsgId(s string) *ChatRecordCreate {
	crc.mutation.SetMsgId(s)
	return crc
}

// SetFromUserId sets the "fromUserId" field.
func (crc *ChatRecordCreate) SetFromUserId(i int) *ChatRecordCreate {
	crc.mutation.SetFromUserId(i)
	return crc
}

// SetToUserId sets the "toUserId" field.
func (crc *ChatRecordCreate) SetToUserId(i int) *ChatRecordCreate {
	crc.mutation.SetToUserId(i)
	return crc
}

// SetMsgType sets the "msgType" field.
func (crc *ChatRecordCreate) SetMsgType(i int) *ChatRecordCreate {
	crc.mutation.SetMsgType(i)
	return crc
}

// SetIsGroup sets the "isGroup" field.
func (crc *ChatRecordCreate) SetIsGroup(b bool) *ChatRecordCreate {
	crc.mutation.SetIsGroup(b)
	return crc
}

// SetNillableIsGroup sets the "isGroup" field if the given value is not nil.
func (crc *ChatRecordCreate) SetNillableIsGroup(b *bool) *ChatRecordCreate {
	if b != nil {
		crc.SetIsGroup(*b)
	}
	return crc
}

// SetGroupId sets the "groupId" field.
func (crc *ChatRecordCreate) SetGroupId(i int) *ChatRecordCreate {
	crc.mutation.SetGroupId(i)
	return crc
}

// SetNillableGroupId sets the "groupId" field if the given value is not nil.
func (crc *ChatRecordCreate) SetNillableGroupId(i *int) *ChatRecordCreate {
	if i != nil {
		crc.SetGroupId(*i)
	}
	return crc
}

// SetCreateTime sets the "createTime" field.
func (crc *ChatRecordCreate) SetCreateTime(t time.Time) *ChatRecordCreate {
	crc.mutation.SetCreateTime(t)
	return crc
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (crc *ChatRecordCreate) SetNillableCreateTime(t *time.Time) *ChatRecordCreate {
	if t != nil {
		crc.SetCreateTime(*t)
	}
	return crc
}

// Mutation returns the ChatRecordMutation object of the builder.
func (crc *ChatRecordCreate) Mutation() *ChatRecordMutation {
	return crc.mutation
}

// Save creates the ChatRecord in the database.
func (crc *ChatRecordCreate) Save(ctx context.Context) (*ChatRecord, error) {
	crc.defaults()
	return withHooks(ctx, crc.sqlSave, crc.mutation, crc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (crc *ChatRecordCreate) SaveX(ctx context.Context) *ChatRecord {
	v, err := crc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crc *ChatRecordCreate) Exec(ctx context.Context) error {
	_, err := crc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crc *ChatRecordCreate) ExecX(ctx context.Context) {
	if err := crc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (crc *ChatRecordCreate) defaults() {
	if _, ok := crc.mutation.IsGroup(); !ok {
		v := chatrecord.DefaultIsGroup
		crc.mutation.SetIsGroup(v)
	}
	if _, ok := crc.mutation.CreateTime(); !ok {
		v := chatrecord.DefaultCreateTime()
		crc.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (crc *ChatRecordCreate) check() error {
	if _, ok := crc.mutation.MsgId(); !ok {
		return &ValidationError{Name: "msgId", err: errors.New(`ent: missing required field "ChatRecord.msgId"`)}
	}
	if v, ok := crc.mutation.MsgId(); ok {
		if err := chatrecord.MsgIdValidator(v); err != nil {
			return &ValidationError{Name: "msgId", err: fmt.Errorf(`ent: validator failed for field "ChatRecord.msgId": %w`, err)}
		}
	}
	if _, ok := crc.mutation.FromUserId(); !ok {
		return &ValidationError{Name: "fromUserId", err: errors.New(`ent: missing required field "ChatRecord.fromUserId"`)}
	}
	if _, ok := crc.mutation.ToUserId(); !ok {
		return &ValidationError{Name: "toUserId", err: errors.New(`ent: missing required field "ChatRecord.toUserId"`)}
	}
	if _, ok := crc.mutation.MsgType(); !ok {
		return &ValidationError{Name: "msgType", err: errors.New(`ent: missing required field "ChatRecord.msgType"`)}
	}
	if _, ok := crc.mutation.IsGroup(); !ok {
		return &ValidationError{Name: "isGroup", err: errors.New(`ent: missing required field "ChatRecord.isGroup"`)}
	}
	if _, ok := crc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "ChatRecord.createTime"`)}
	}
	return nil
}

func (crc *ChatRecordCreate) sqlSave(ctx context.Context) (*ChatRecord, error) {
	if err := crc.check(); err != nil {
		return nil, err
	}
	_node, _spec := crc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	crc.mutation.id = &_node.ID
	crc.mutation.done = true
	return _node, nil
}

func (crc *ChatRecordCreate) createSpec() (*ChatRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatRecord{config: crc.config}
		_spec = sqlgraph.NewCreateSpec(chatrecord.Table, sqlgraph.NewFieldSpec(chatrecord.FieldID, field.TypeInt))
	)
	if value, ok := crc.mutation.MsgId(); ok {
		_spec.SetField(chatrecord.FieldMsgId, field.TypeString, value)
		_node.MsgId = value
	}
	if value, ok := crc.mutation.FromUserId(); ok {
		_spec.SetField(chatrecord.FieldFromUserId, field.TypeInt, value)
		_node.FromUserId = value
	}
	if value, ok := crc.mutation.ToUserId(); ok {
		_spec.SetField(chatrecord.FieldToUserId, field.TypeInt, value)
		_node.ToUserId = value
	}
	if value, ok := crc.mutation.MsgType(); ok {
		_spec.SetField(chatrecord.FieldMsgType, field.TypeInt, value)
		_node.MsgType = value
	}
	if value, ok := crc.mutation.IsGroup(); ok {
		_spec.SetField(chatrecord.FieldIsGroup, field.TypeBool, value)
		_node.IsGroup = value
	}
	if value, ok := crc.mutation.GroupId(); ok {
		_spec.SetField(chatrecord.FieldGroupId, field.TypeInt, value)
		_node.GroupId = value
	}
	if value, ok := crc.mutation.CreateTime(); ok {
		_spec.SetField(chatrecord.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	return _node, _spec
}

// ChatRecordCreateBulk is the builder for creating many ChatRecord entities in bulk.
type ChatRecordCreateBulk struct {
	config
	err      error
	builders []*ChatRecordCreate
}

// Save creates the ChatRecord entities in the database.
func (crcb *ChatRecordCreateBulk) Save(ctx context.Context) ([]*ChatRecord, error) {
	if crcb.err != nil {
		return nil, crcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(crcb.builders))
	nodes := make([]*ChatRecord, len(crcb.builders))
	mutators := make([]Mutator, len(crcb.builders))
	for i := range crcb.builders {
		func(i int, root context.Context) {
			builder := crcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crcb *ChatRecordCreateBulk) SaveX(ctx context.Context) []*ChatRecord {
	v, err := crcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crcb *ChatRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := crcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crcb *ChatRecordCreateBulk) ExecX(ctx context.Context) {
	if err := crcb.Exec(ctx); err != nil {
		panic(err)
	}
}
