// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gochat_server/ent/friendrelationship"
	"gochat_server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendRelationshipDelete is the builder for deleting a FriendRelationship entity.
type FriendRelationshipDelete struct {
	config
	hooks    []Hook
	mutation *FriendRelationshipMutation
}

// Where appends a list predicates to the FriendRelationshipDelete builder.
func (frd *FriendRelationshipDelete) Where(ps ...predicate.FriendRelationship) *FriendRelationshipDelete {
	frd.mutation.Where(ps...)
	return frd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (frd *FriendRelationshipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, frd.sqlExec, frd.mutation, frd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (frd *FriendRelationshipDelete) ExecX(ctx context.Context) int {
	n, err := frd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (frd *FriendRelationshipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(friendrelationship.Table, sqlgraph.NewFieldSpec(friendrelationship.FieldID, field.TypeInt))
	if ps := frd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, frd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	frd.mutation.done = true
	return affected, err
}

// FriendRelationshipDeleteOne is the builder for deleting a single FriendRelationship entity.
type FriendRelationshipDeleteOne struct {
	frd *FriendRelationshipDelete
}

// Where appends a list predicates to the FriendRelationshipDelete builder.
func (frdo *FriendRelationshipDeleteOne) Where(ps ...predicate.FriendRelationship) *FriendRelationshipDeleteOne {
	frdo.frd.mutation.Where(ps...)
	return frdo
}

// Exec executes the deletion query.
func (frdo *FriendRelationshipDeleteOne) Exec(ctx context.Context) error {
	n, err := frdo.frd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{friendrelationship.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (frdo *FriendRelationshipDeleteOne) ExecX(ctx context.Context) {
	if err := frdo.Exec(ctx); err != nil {
		panic(err)
	}
}
