// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gochat_server/ent/friendrequest"
	"gochat_server/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendRequestQuery is the builder for querying FriendRequest entities.
type FriendRequestQuery struct {
	config
	ctx        *QueryContext
	order      []friendrequest.OrderOption
	inters     []Interceptor
	predicates []predicate.FriendRequest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FriendRequestQuery builder.
func (frq *FriendRequestQuery) Where(ps ...predicate.FriendRequest) *FriendRequestQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FriendRequestQuery) Limit(limit int) *FriendRequestQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FriendRequestQuery) Offset(offset int) *FriendRequestQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FriendRequestQuery) Unique(unique bool) *FriendRequestQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FriendRequestQuery) Order(o ...friendrequest.OrderOption) *FriendRequestQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// First returns the first FriendRequest entity from the query.
// Returns a *NotFoundError when no FriendRequest was found.
func (frq *FriendRequestQuery) First(ctx context.Context) (*FriendRequest, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{friendrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FriendRequestQuery) FirstX(ctx context.Context) *FriendRequest {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FriendRequest ID from the query.
// Returns a *NotFoundError when no FriendRequest ID was found.
func (frq *FriendRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{friendrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FriendRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FriendRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FriendRequest entity is found.
// Returns a *NotFoundError when no FriendRequest entities are found.
func (frq *FriendRequestQuery) Only(ctx context.Context) (*FriendRequest, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{friendrequest.Label}
	default:
		return nil, &NotSingularError{friendrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FriendRequestQuery) OnlyX(ctx context.Context) *FriendRequest {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FriendRequest ID in the query.
// Returns a *NotSingularError when more than one FriendRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FriendRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{friendrequest.Label}
	default:
		err = &NotSingularError{friendrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FriendRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FriendRequests.
func (frq *FriendRequestQuery) All(ctx context.Context) ([]*FriendRequest, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryAll)
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FriendRequest, *FriendRequestQuery]()
	return withInterceptors[[]*FriendRequest](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FriendRequestQuery) AllX(ctx context.Context) []*FriendRequest {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FriendRequest IDs.
func (frq *FriendRequestQuery) IDs(ctx context.Context) (ids []int, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryIDs)
	if err = frq.Select(friendrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FriendRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FriendRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryCount)
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FriendRequestQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FriendRequestQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FriendRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryExist)
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FriendRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FriendRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FriendRequestQuery) Clone() *FriendRequestQuery {
	if frq == nil {
		return nil
	}
	return &FriendRequestQuery{
		config:     frq.config,
		ctx:        frq.ctx.Clone(),
		order:      append([]friendrequest.OrderOption{}, frq.order...),
		inters:     append([]Interceptor{}, frq.inters...),
		predicates: append([]predicate.FriendRequest{}, frq.predicates...),
		// clone intermediate query.
		sql:  frq.sql.Clone(),
		path: frq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FromUserId int `json:"fromUserId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FriendRequest.Query().
//		GroupBy(friendrequest.FieldFromUserId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (frq *FriendRequestQuery) GroupBy(field string, fields ...string) *FriendRequestGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FriendRequestGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = friendrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FromUserId int `json:"fromUserId,omitempty"`
//	}
//
//	client.FriendRequest.Query().
//		Select(friendrequest.FieldFromUserId).
//		Scan(ctx, &v)
func (frq *FriendRequestQuery) Select(fields ...string) *FriendRequestSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FriendRequestSelect{FriendRequestQuery: frq}
	sbuild.label = friendrequest.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FriendRequestSelect configured with the given aggregations.
func (frq *FriendRequestQuery) Aggregate(fns ...AggregateFunc) *FriendRequestSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FriendRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !friendrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FriendRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FriendRequest, error) {
	var (
		nodes = []*FriendRequest{}
		_spec = frq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FriendRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FriendRequest{config: frq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (frq *FriendRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FriendRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(friendrequest.Table, friendrequest.Columns, sqlgraph.NewFieldSpec(friendrequest.FieldID, field.TypeInt))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendrequest.FieldID)
		for i := range fields {
			if fields[i] != friendrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FriendRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(friendrequest.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = friendrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FriendRequestGroupBy is the group-by builder for FriendRequest entities.
type FriendRequestGroupBy struct {
	selector
	build *FriendRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FriendRequestGroupBy) Aggregate(fns ...AggregateFunc) *FriendRequestGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FriendRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, ent.OpQueryGroupBy)
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendRequestQuery, *FriendRequestGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FriendRequestGroupBy) sqlScan(ctx context.Context, root *FriendRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FriendRequestSelect is the builder for selecting fields of FriendRequest entities.
type FriendRequestSelect struct {
	*FriendRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FriendRequestSelect) Aggregate(fns ...AggregateFunc) *FriendRequestSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FriendRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, ent.OpQuerySelect)
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendRequestQuery, *FriendRequestSelect](ctx, frs.FriendRequestQuery, frs, frs.inters, v)
}

func (frs *FriendRequestSelect) sqlScan(ctx context.Context, root *FriendRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
