// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gochat_server/ent/friendrelationship"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendRelationshipCreate is the builder for creating a FriendRelationship entity.
type FriendRelationshipCreate struct {
	config
	mutation *FriendRelationshipMutation
	hooks    []Hook
}

// SetUserId sets the "userId" field.
func (frc *FriendRelationshipCreate) SetUserId(i int) *FriendRelationshipCreate {
	frc.mutation.SetUserId(i)
	return frc
}

// SetFriendId sets the "friendId" field.
func (frc *FriendRelationshipCreate) SetFriendId(i int) *FriendRelationshipCreate {
	frc.mutation.SetFriendId(i)
	return frc
}

// SetRemarkName sets the "remarkName" field.
func (frc *FriendRelationshipCreate) SetRemarkName(s string) *FriendRelationshipCreate {
	frc.mutation.SetRemarkName(s)
	return frc
}

// SetNillableRemarkName sets the "remarkName" field if the given value is not nil.
func (frc *FriendRelationshipCreate) SetNillableRemarkName(s *string) *FriendRelationshipCreate {
	if s != nil {
		frc.SetRemarkName(*s)
	}
	return frc
}

// SetCategory sets the "category" field.
func (frc *FriendRelationshipCreate) SetCategory(s string) *FriendRelationshipCreate {
	frc.mutation.SetCategory(s)
	return frc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (frc *FriendRelationshipCreate) SetNillableCategory(s *string) *FriendRelationshipCreate {
	if s != nil {
		frc.SetCategory(*s)
	}
	return frc
}

// SetTags sets the "tags" field.
func (frc *FriendRelationshipCreate) SetTags(s []string) *FriendRelationshipCreate {
	frc.mutation.SetTags(s)
	return frc
}

// Mutation returns the FriendRelationshipMutation object of the builder.
func (frc *FriendRelationshipCreate) Mutation() *FriendRelationshipMutation {
	return frc.mutation
}

// Save creates the FriendRelationship in the database.
func (frc *FriendRelationshipCreate) Save(ctx context.Context) (*FriendRelationship, error) {
	return withHooks(ctx, frc.sqlSave, frc.mutation, frc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (frc *FriendRelationshipCreate) SaveX(ctx context.Context) *FriendRelationship {
	v, err := frc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frc *FriendRelationshipCreate) Exec(ctx context.Context) error {
	_, err := frc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frc *FriendRelationshipCreate) ExecX(ctx context.Context) {
	if err := frc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (frc *FriendRelationshipCreate) check() error {
	if _, ok := frc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "FriendRelationship.userId"`)}
	}
	if _, ok := frc.mutation.FriendId(); !ok {
		return &ValidationError{Name: "friendId", err: errors.New(`ent: missing required field "FriendRelationship.friendId"`)}
	}
	return nil
}

func (frc *FriendRelationshipCreate) sqlSave(ctx context.Context) (*FriendRelationship, error) {
	if err := frc.check(); err != nil {
		return nil, err
	}
	_node, _spec := frc.createSpec()
	if err := sqlgraph.CreateNode(ctx, frc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	frc.mutation.id = &_node.ID
	frc.mutation.done = true
	return _node, nil
}

func (frc *FriendRelationshipCreate) createSpec() (*FriendRelationship, *sqlgraph.CreateSpec) {
	var (
		_node = &FriendRelationship{config: frc.config}
		_spec = sqlgraph.NewCreateSpec(friendrelationship.Table, sqlgraph.NewFieldSpec(friendrelationship.FieldID, field.TypeInt))
	)
	if value, ok := frc.mutation.UserId(); ok {
		_spec.SetField(friendrelationship.FieldUserId, field.TypeInt, value)
		_node.UserId = value
	}
	if value, ok := frc.mutation.FriendId(); ok {
		_spec.SetField(friendrelationship.FieldFriendId, field.TypeInt, value)
		_node.FriendId = value
	}
	if value, ok := frc.mutation.RemarkName(); ok {
		_spec.SetField(friendrelationship.FieldRemarkName, field.TypeString, value)
		_node.RemarkName = value
	}
	if value, ok := frc.mutation.Category(); ok {
		_spec.SetField(friendrelationship.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := frc.mutation.Tags(); ok {
		_spec.SetField(friendrelationship.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	return _node, _spec
}

// FriendRelationshipCreateBulk is the builder for creating many FriendRelationship entities in bulk.
type FriendRelationshipCreateBulk struct {
	config
	err      error
	builders []*FriendRelationshipCreate
}

// Save creates the FriendRelationship entities in the database.
func (frcb *FriendRelationshipCreateBulk) Save(ctx context.Context) ([]*FriendRelationship, error) {
	if frcb.err != nil {
		return nil, frcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(frcb.builders))
	nodes := make([]*FriendRelationship, len(frcb.builders))
	mutators := make([]Mutator, len(frcb.builders))
	for i := range frcb.builders {
		func(i int, root context.Context) {
			builder := frcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FriendRelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, frcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, frcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, frcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (frcb *FriendRelationshipCreateBulk) SaveX(ctx context.Context) []*FriendRelationship {
	v, err := frcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frcb *FriendRelationshipCreateBulk) Exec(ctx context.Context) error {
	_, err := frcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frcb *FriendRelationshipCreateBulk) ExecX(ctx context.Context) {
	if err := frcb.Exec(ctx); err != nil {
		panic(err)
	}
}
