// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gochat_server/ent/groupchatrecord"
	"gochat_server/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupChatRecordQuery is the builder for querying GroupChatRecord entities.
type GroupChatRecordQuery struct {
	config
	ctx        *QueryContext
	order      []groupchatrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.GroupChatRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupChatRecordQuery builder.
func (gcrq *GroupChatRecordQuery) Where(ps ...predicate.GroupChatRecord) *GroupChatRecordQuery {
	gcrq.predicates = append(gcrq.predicates, ps...)
	return gcrq
}

// Limit the number of records to be returned by this query.
func (gcrq *GroupChatRecordQuery) Limit(limit int) *GroupChatRecordQuery {
	gcrq.ctx.Limit = &limit
	return gcrq
}

// Offset to start from.
func (gcrq *GroupChatRecordQuery) Offset(offset int) *GroupChatRecordQuery {
	gcrq.ctx.Offset = &offset
	return gcrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gcrq *GroupChatRecordQuery) Unique(unique bool) *GroupChatRecordQuery {
	gcrq.ctx.Unique = &unique
	return gcrq
}

// Order specifies how the records should be ordered.
func (gcrq *GroupChatRecordQuery) Order(o ...groupchatrecord.OrderOption) *GroupChatRecordQuery {
	gcrq.order = append(gcrq.order, o...)
	return gcrq
}

// First returns the first GroupChatRecord entity from the query.
// Returns a *NotFoundError when no GroupChatRecord was found.
func (gcrq *GroupChatRecordQuery) First(ctx context.Context) (*GroupChatRecord, error) {
	nodes, err := gcrq.Limit(1).All(setContextOp(ctx, gcrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupchatrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) FirstX(ctx context.Context) *GroupChatRecord {
	node, err := gcrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupChatRecord ID from the query.
// Returns a *NotFoundError when no GroupChatRecord ID was found.
func (gcrq *GroupChatRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcrq.Limit(1).IDs(setContextOp(ctx, gcrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupchatrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := gcrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupChatRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupChatRecord entity is found.
// Returns a *NotFoundError when no GroupChatRecord entities are found.
func (gcrq *GroupChatRecordQuery) Only(ctx context.Context) (*GroupChatRecord, error) {
	nodes, err := gcrq.Limit(2).All(setContextOp(ctx, gcrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupchatrecord.Label}
	default:
		return nil, &NotSingularError{groupchatrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) OnlyX(ctx context.Context) *GroupChatRecord {
	node, err := gcrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupChatRecord ID in the query.
// Returns a *NotSingularError when more than one GroupChatRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (gcrq *GroupChatRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcrq.Limit(2).IDs(setContextOp(ctx, gcrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupchatrecord.Label}
	default:
		err = &NotSingularError{groupchatrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := gcrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupChatRecords.
func (gcrq *GroupChatRecordQuery) All(ctx context.Context) ([]*GroupChatRecord, error) {
	ctx = setContextOp(ctx, gcrq.ctx, ent.OpQueryAll)
	if err := gcrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupChatRecord, *GroupChatRecordQuery]()
	return withInterceptors[[]*GroupChatRecord](ctx, gcrq, qr, gcrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) AllX(ctx context.Context) []*GroupChatRecord {
	nodes, err := gcrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupChatRecord IDs.
func (gcrq *GroupChatRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if gcrq.ctx.Unique == nil && gcrq.path != nil {
		gcrq.Unique(true)
	}
	ctx = setContextOp(ctx, gcrq.ctx, ent.OpQueryIDs)
	if err = gcrq.Select(groupchatrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := gcrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gcrq *GroupChatRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gcrq.ctx, ent.OpQueryCount)
	if err := gcrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gcrq, querierCount[*GroupChatRecordQuery](), gcrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) CountX(ctx context.Context) int {
	count, err := gcrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gcrq *GroupChatRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gcrq.ctx, ent.OpQueryExist)
	switch _, err := gcrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gcrq *GroupChatRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := gcrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupChatRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gcrq *GroupChatRecordQuery) Clone() *GroupChatRecordQuery {
	if gcrq == nil {
		return nil
	}
	return &GroupChatRecordQuery{
		config:     gcrq.config,
		ctx:        gcrq.ctx.Clone(),
		order:      append([]groupchatrecord.OrderOption{}, gcrq.order...),
		inters:     append([]Interceptor{}, gcrq.inters...),
		predicates: append([]predicate.GroupChatRecord{}, gcrq.predicates...),
		// clone intermediate query.
		sql:  gcrq.sql.Clone(),
		path: gcrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupChatRecord.Query().
//		GroupBy(groupchatrecord.FieldMsgId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gcrq *GroupChatRecordQuery) GroupBy(field string, fields ...string) *GroupChatRecordGroupBy {
	gcrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupChatRecordGroupBy{build: gcrq}
	grbuild.flds = &gcrq.ctx.Fields
	grbuild.label = groupchatrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//	}
//
//	client.GroupChatRecord.Query().
//		Select(groupchatrecord.FieldMsgId).
//		Scan(ctx, &v)
func (gcrq *GroupChatRecordQuery) Select(fields ...string) *GroupChatRecordSelect {
	gcrq.ctx.Fields = append(gcrq.ctx.Fields, fields...)
	sbuild := &GroupChatRecordSelect{GroupChatRecordQuery: gcrq}
	sbuild.label = groupchatrecord.Label
	sbuild.flds, sbuild.scan = &gcrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupChatRecordSelect configured with the given aggregations.
func (gcrq *GroupChatRecordQuery) Aggregate(fns ...AggregateFunc) *GroupChatRecordSelect {
	return gcrq.Select().Aggregate(fns...)
}

func (gcrq *GroupChatRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gcrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gcrq); err != nil {
				return err
			}
		}
	}
	for _, f := range gcrq.ctx.Fields {
		if !groupchatrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gcrq.path != nil {
		prev, err := gcrq.path(ctx)
		if err != nil {
			return err
		}
		gcrq.sql = prev
	}
	return nil
}

func (gcrq *GroupChatRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupChatRecord, error) {
	var (
		nodes = []*GroupChatRecord{}
		_spec = gcrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupChatRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupChatRecord{config: gcrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gcrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gcrq *GroupChatRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gcrq.querySpec()
	_spec.Node.Columns = gcrq.ctx.Fields
	if len(gcrq.ctx.Fields) > 0 {
		_spec.Unique = gcrq.ctx.Unique != nil && *gcrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gcrq.driver, _spec)
}

func (gcrq *GroupChatRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupchatrecord.Table, groupchatrecord.Columns, sqlgraph.NewFieldSpec(groupchatrecord.FieldID, field.TypeInt))
	_spec.From = gcrq.sql
	if unique := gcrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gcrq.path != nil {
		_spec.Unique = true
	}
	if fields := gcrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupchatrecord.FieldID)
		for i := range fields {
			if fields[i] != groupchatrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gcrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gcrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gcrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gcrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gcrq *GroupChatRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gcrq.driver.Dialect())
	t1 := builder.Table(groupchatrecord.Table)
	columns := gcrq.ctx.Fields
	if len(columns) == 0 {
		columns = groupchatrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gcrq.sql != nil {
		selector = gcrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gcrq.ctx.Unique != nil && *gcrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gcrq.predicates {
		p(selector)
	}
	for _, p := range gcrq.order {
		p(selector)
	}
	if offset := gcrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gcrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupChatRecordGroupBy is the group-by builder for GroupChatRecord entities.
type GroupChatRecordGroupBy struct {
	selector
	build *GroupChatRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gcrgb *GroupChatRecordGroupBy) Aggregate(fns ...AggregateFunc) *GroupChatRecordGroupBy {
	gcrgb.fns = append(gcrgb.fns, fns...)
	return gcrgb
}

// Scan applies the selector query and scans the result into the given value.
func (gcrgb *GroupChatRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcrgb.build.ctx, ent.OpQueryGroupBy)
	if err := gcrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupChatRecordQuery, *GroupChatRecordGroupBy](ctx, gcrgb.build, gcrgb, gcrgb.build.inters, v)
}

func (gcrgb *GroupChatRecordGroupBy) sqlScan(ctx context.Context, root *GroupChatRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gcrgb.fns))
	for _, fn := range gcrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gcrgb.flds)+len(gcrgb.fns))
		for _, f := range *gcrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gcrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupChatRecordSelect is the builder for selecting fields of GroupChatRecord entities.
type GroupChatRecordSelect struct {
	*GroupChatRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gcrs *GroupChatRecordSelect) Aggregate(fns ...AggregateFunc) *GroupChatRecordSelect {
	gcrs.fns = append(gcrs.fns, fns...)
	return gcrs
}

// Scan applies the selector query and scans the result into the given value.
func (gcrs *GroupChatRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcrs.ctx, ent.OpQuerySelect)
	if err := gcrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupChatRecordQuery, *GroupChatRecordSelect](ctx, gcrs.GroupChatRecordQuery, gcrs, gcrs.inters, v)
}

func (gcrs *GroupChatRecordSelect) sqlScan(ctx context.Context, root *GroupChatRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gcrs.fns))
	for _, fn := range gcrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gcrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
