// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gochat_server/ent/imagemessage"
	"gochat_server/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImageMessageQuery is the builder for querying ImageMessage entities.
type ImageMessageQuery struct {
	config
	ctx        *QueryContext
	order      []imagemessage.OrderOption
	inters     []Interceptor
	predicates []predicate.ImageMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ImageMessageQuery builder.
func (imq *ImageMessageQuery) Where(ps ...predicate.ImageMessage) *ImageMessageQuery {
	imq.predicates = append(imq.predicates, ps...)
	return imq
}

// Limit the number of records to be returned by this query.
func (imq *ImageMessageQuery) Limit(limit int) *ImageMessageQuery {
	imq.ctx.Limit = &limit
	return imq
}

// Offset to start from.
func (imq *ImageMessageQuery) Offset(offset int) *ImageMessageQuery {
	imq.ctx.Offset = &offset
	return imq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (imq *ImageMessageQuery) Unique(unique bool) *ImageMessageQuery {
	imq.ctx.Unique = &unique
	return imq
}

// Order specifies how the records should be ordered.
func (imq *ImageMessageQuery) Order(o ...imagemessage.OrderOption) *ImageMessageQuery {
	imq.order = append(imq.order, o...)
	return imq
}

// First returns the first ImageMessage entity from the query.
// Returns a *NotFoundError when no ImageMessage was found.
func (imq *ImageMessageQuery) First(ctx context.Context) (*ImageMessage, error) {
	nodes, err := imq.Limit(1).All(setContextOp(ctx, imq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{imagemessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (imq *ImageMessageQuery) FirstX(ctx context.Context) *ImageMessage {
	node, err := imq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ImageMessage ID from the query.
// Returns a *NotFoundError when no ImageMessage ID was found.
func (imq *ImageMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = imq.Limit(1).IDs(setContextOp(ctx, imq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{imagemessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (imq *ImageMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := imq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ImageMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ImageMessage entity is found.
// Returns a *NotFoundError when no ImageMessage entities are found.
func (imq *ImageMessageQuery) Only(ctx context.Context) (*ImageMessage, error) {
	nodes, err := imq.Limit(2).All(setContextOp(ctx, imq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{imagemessage.Label}
	default:
		return nil, &NotSingularError{imagemessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (imq *ImageMessageQuery) OnlyX(ctx context.Context) *ImageMessage {
	node, err := imq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ImageMessage ID in the query.
// Returns a *NotSingularError when more than one ImageMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (imq *ImageMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = imq.Limit(2).IDs(setContextOp(ctx, imq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{imagemessage.Label}
	default:
		err = &NotSingularError{imagemessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (imq *ImageMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := imq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImageMessages.
func (imq *ImageMessageQuery) All(ctx context.Context) ([]*ImageMessage, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryAll)
	if err := imq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ImageMessage, *ImageMessageQuery]()
	return withInterceptors[[]*ImageMessage](ctx, imq, qr, imq.inters)
}

// AllX is like All, but panics if an error occurs.
func (imq *ImageMessageQuery) AllX(ctx context.Context) []*ImageMessage {
	nodes, err := imq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ImageMessage IDs.
func (imq *ImageMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if imq.ctx.Unique == nil && imq.path != nil {
		imq.Unique(true)
	}
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryIDs)
	if err = imq.Select(imagemessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (imq *ImageMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := imq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (imq *ImageMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryCount)
	if err := imq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, imq, querierCount[*ImageMessageQuery](), imq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (imq *ImageMessageQuery) CountX(ctx context.Context) int {
	count, err := imq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (imq *ImageMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryExist)
	switch _, err := imq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (imq *ImageMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := imq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ImageMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (imq *ImageMessageQuery) Clone() *ImageMessageQuery {
	if imq == nil {
		return nil
	}
	return &ImageMessageQuery{
		config:     imq.config,
		ctx:        imq.ctx.Clone(),
		order:      append([]imagemessage.OrderOption{}, imq.order...),
		inters:     append([]Interceptor{}, imq.inters...),
		predicates: append([]predicate.ImageMessage{}, imq.predicates...),
		// clone intermediate query.
		sql:  imq.sql.Clone(),
		path: imq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ImageMessage.Query().
//		GroupBy(imagemessage.FieldMsgId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (imq *ImageMessageQuery) GroupBy(field string, fields ...string) *ImageMessageGroupBy {
	imq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ImageMessageGroupBy{build: imq}
	grbuild.flds = &imq.ctx.Fields
	grbuild.label = imagemessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//	}
//
//	client.ImageMessage.Query().
//		Select(imagemessage.FieldMsgId).
//		Scan(ctx, &v)
func (imq *ImageMessageQuery) Select(fields ...string) *ImageMessageSelect {
	imq.ctx.Fields = append(imq.ctx.Fields, fields...)
	sbuild := &ImageMessageSelect{ImageMessageQuery: imq}
	sbuild.label = imagemessage.Label
	sbuild.flds, sbuild.scan = &imq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ImageMessageSelect configured with the given aggregations.
func (imq *ImageMessageQuery) Aggregate(fns ...AggregateFunc) *ImageMessageSelect {
	return imq.Select().Aggregate(fns...)
}

func (imq *ImageMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range imq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, imq); err != nil {
				return err
			}
		}
	}
	for _, f := range imq.ctx.Fields {
		if !imagemessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if imq.path != nil {
		prev, err := imq.path(ctx)
		if err != nil {
			return err
		}
		imq.sql = prev
	}
	return nil
}

func (imq *ImageMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ImageMessage, error) {
	var (
		nodes = []*ImageMessage{}
		_spec = imq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ImageMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ImageMessage{config: imq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, imq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (imq *ImageMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := imq.querySpec()
	_spec.Node.Columns = imq.ctx.Fields
	if len(imq.ctx.Fields) > 0 {
		_spec.Unique = imq.ctx.Unique != nil && *imq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, imq.driver, _spec)
}

func (imq *ImageMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(imagemessage.Table, imagemessage.Columns, sqlgraph.NewFieldSpec(imagemessage.FieldID, field.TypeInt))
	_spec.From = imq.sql
	if unique := imq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if imq.path != nil {
		_spec.Unique = true
	}
	if fields := imq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagemessage.FieldID)
		for i := range fields {
			if fields[i] != imagemessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := imq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := imq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := imq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := imq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (imq *ImageMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(imq.driver.Dialect())
	t1 := builder.Table(imagemessage.Table)
	columns := imq.ctx.Fields
	if len(columns) == 0 {
		columns = imagemessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if imq.sql != nil {
		selector = imq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if imq.ctx.Unique != nil && *imq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range imq.predicates {
		p(selector)
	}
	for _, p := range imq.order {
		p(selector)
	}
	if offset := imq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := imq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImageMessageGroupBy is the group-by builder for ImageMessage entities.
type ImageMessageGroupBy struct {
	selector
	build *ImageMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (imgb *ImageMessageGroupBy) Aggregate(fns ...AggregateFunc) *ImageMessageGroupBy {
	imgb.fns = append(imgb.fns, fns...)
	return imgb
}

// Scan applies the selector query and scans the result into the given value.
func (imgb *ImageMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, imgb.build.ctx, ent.OpQueryGroupBy)
	if err := imgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImageMessageQuery, *ImageMessageGroupBy](ctx, imgb.build, imgb, imgb.build.inters, v)
}

func (imgb *ImageMessageGroupBy) sqlScan(ctx context.Context, root *ImageMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(imgb.fns))
	for _, fn := range imgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*imgb.flds)+len(imgb.fns))
		for _, f := range *imgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*imgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := imgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ImageMessageSelect is the builder for selecting fields of ImageMessage entities.
type ImageMessageSelect struct {
	*ImageMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ims *ImageMessageSelect) Aggregate(fns ...AggregateFunc) *ImageMessageSelect {
	ims.fns = append(ims.fns, fns...)
	return ims
}

// Scan applies the selector query and scans the result into the given value.
func (ims *ImageMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ims.ctx, ent.OpQuerySelect)
	if err := ims.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImageMessageQuery, *ImageMessageSelect](ctx, ims.ImageMessageQuery, ims, ims.inters, v)
}

func (ims *ImageMessageSelect) sqlScan(ctx context.Context, root *ImageMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ims.fns))
	for _, fn := range ims.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ims.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ims.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
