// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gochat_server/ent/chatrecord"
	"gochat_server/ent/friendrelationship"
	"gochat_server/ent/group"
	"gochat_server/ent/groupchatrecord"
	"gochat_server/ent/imagemessage"
	"gochat_server/ent/schema"
	"gochat_server/ent/textmessage"
	"gochat_server/ent/user"
	"gochat_server/ent/videomessage"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatrecordFields := schema.ChatRecord{}.Fields()
	_ = chatrecordFields
	// chatrecordDescMsgId is the schema descriptor for msgId field.
	chatrecordDescMsgId := chatrecordFields[0].Descriptor()
	// chatrecord.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	chatrecord.MsgIdValidator = chatrecordDescMsgId.Validators[0].(func(string) error)
	// chatrecordDescFromUserId is the schema descriptor for fromUserId field.
	chatrecordDescFromUserId := chatrecordFields[1].Descriptor()
	// chatrecord.FromUserIdValidator is a validator for the "fromUserId" field. It is called by the builders before save.
	chatrecord.FromUserIdValidator = chatrecordDescFromUserId.Validators[0].(func(string) error)
	// chatrecordDescToUserId is the schema descriptor for toUserId field.
	chatrecordDescToUserId := chatrecordFields[2].Descriptor()
	// chatrecord.ToUserIdValidator is a validator for the "toUserId" field. It is called by the builders before save.
	chatrecord.ToUserIdValidator = chatrecordDescToUserId.Validators[0].(func(string) error)
	// chatrecordDescMsgType is the schema descriptor for msgType field.
	chatrecordDescMsgType := chatrecordFields[3].Descriptor()
	// chatrecord.MsgTypeValidator is a validator for the "msgType" field. It is called by the builders before save.
	chatrecord.MsgTypeValidator = chatrecordDescMsgType.Validators[0].(func(string) error)
	// chatrecordDescCreateTime is the schema descriptor for createTime field.
	chatrecordDescCreateTime := chatrecordFields[4].Descriptor()
	// chatrecord.DefaultCreateTime holds the default value on creation for the createTime field.
	chatrecord.DefaultCreateTime = chatrecordDescCreateTime.Default.(func() time.Time)
	friendrelationshipFields := schema.FriendRelationship{}.Fields()
	_ = friendrelationshipFields
	// friendrelationshipDescUserId is the schema descriptor for userId field.
	friendrelationshipDescUserId := friendrelationshipFields[0].Descriptor()
	// friendrelationship.UserIdValidator is a validator for the "userId" field. It is called by the builders before save.
	friendrelationship.UserIdValidator = friendrelationshipDescUserId.Validators[0].(func(string) error)
	// friendrelationshipDescFriendId is the schema descriptor for friendId field.
	friendrelationshipDescFriendId := friendrelationshipFields[1].Descriptor()
	// friendrelationship.FriendIdValidator is a validator for the "friendId" field. It is called by the builders before save.
	friendrelationship.FriendIdValidator = friendrelationshipDescFriendId.Validators[0].(func(string) error)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescGroupId is the schema descriptor for groupId field.
	groupDescGroupId := groupFields[0].Descriptor()
	// group.GroupIdValidator is a validator for the "groupId" field. It is called by the builders before save.
	group.GroupIdValidator = groupDescGroupId.Validators[0].(func(string) error)
	// groupDescGroupName is the schema descriptor for groupName field.
	groupDescGroupName := groupFields[1].Descriptor()
	// group.GroupNameValidator is a validator for the "groupName" field. It is called by the builders before save.
	group.GroupNameValidator = groupDescGroupName.Validators[0].(func(string) error)
	// groupDescOwnerId is the schema descriptor for ownerId field.
	groupDescOwnerId := groupFields[2].Descriptor()
	// group.OwnerIdValidator is a validator for the "ownerId" field. It is called by the builders before save.
	group.OwnerIdValidator = groupDescOwnerId.Validators[0].(func(string) error)
	// groupDescCreateUserId is the schema descriptor for createUserId field.
	groupDescCreateUserId := groupFields[3].Descriptor()
	// group.CreateUserIdValidator is a validator for the "createUserId" field. It is called by the builders before save.
	group.CreateUserIdValidator = groupDescCreateUserId.Validators[0].(func(string) error)
	// groupDescCreateTime is the schema descriptor for createTime field.
	groupDescCreateTime := groupFields[4].Descriptor()
	// group.CreateTimeValidator is a validator for the "createTime" field. It is called by the builders before save.
	group.CreateTimeValidator = groupDescCreateTime.Validators[0].(func(string) error)
	groupchatrecordFields := schema.GroupChatRecord{}.Fields()
	_ = groupchatrecordFields
	// groupchatrecordDescMsgId is the schema descriptor for msgId field.
	groupchatrecordDescMsgId := groupchatrecordFields[0].Descriptor()
	// groupchatrecord.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	groupchatrecord.MsgIdValidator = groupchatrecordDescMsgId.Validators[0].(func(string) error)
	// groupchatrecordDescFromUserId is the schema descriptor for fromUserId field.
	groupchatrecordDescFromUserId := groupchatrecordFields[1].Descriptor()
	// groupchatrecord.FromUserIdValidator is a validator for the "fromUserId" field. It is called by the builders before save.
	groupchatrecord.FromUserIdValidator = groupchatrecordDescFromUserId.Validators[0].(func(string) error)
	// groupchatrecordDescGroupId is the schema descriptor for groupId field.
	groupchatrecordDescGroupId := groupchatrecordFields[2].Descriptor()
	// groupchatrecord.GroupIdValidator is a validator for the "groupId" field. It is called by the builders before save.
	groupchatrecord.GroupIdValidator = groupchatrecordDescGroupId.Validators[0].(func(string) error)
	// groupchatrecordDescMsgType is the schema descriptor for msgType field.
	groupchatrecordDescMsgType := groupchatrecordFields[3].Descriptor()
	// groupchatrecord.MsgTypeValidator is a validator for the "msgType" field. It is called by the builders before save.
	groupchatrecord.MsgTypeValidator = groupchatrecordDescMsgType.Validators[0].(func(string) error)
	// groupchatrecordDescCreateTime is the schema descriptor for createTime field.
	groupchatrecordDescCreateTime := groupchatrecordFields[4].Descriptor()
	// groupchatrecord.DefaultCreateTime holds the default value on creation for the createTime field.
	groupchatrecord.DefaultCreateTime = groupchatrecordDescCreateTime.Default.(func() time.Time)
	imagemessageFields := schema.ImageMessage{}.Fields()
	_ = imagemessageFields
	// imagemessageDescMsgId is the schema descriptor for msgId field.
	imagemessageDescMsgId := imagemessageFields[0].Descriptor()
	// imagemessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	imagemessage.MsgIdValidator = imagemessageDescMsgId.Validators[0].(func(string) error)
	// imagemessageDescImageUrl is the schema descriptor for imageUrl field.
	imagemessageDescImageUrl := imagemessageFields[1].Descriptor()
	// imagemessage.ImageUrlValidator is a validator for the "imageUrl" field. It is called by the builders before save.
	imagemessage.ImageUrlValidator = imagemessageDescImageUrl.Validators[0].(func(string) error)
	textmessageFields := schema.TextMessage{}.Fields()
	_ = textmessageFields
	// textmessageDescMsgId is the schema descriptor for msgId field.
	textmessageDescMsgId := textmessageFields[0].Descriptor()
	// textmessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	textmessage.MsgIdValidator = textmessageDescMsgId.Validators[0].(func(string) error)
	// textmessageDescText is the schema descriptor for text field.
	textmessageDescText := textmessageFields[1].Descriptor()
	// textmessage.TextValidator is a validator for the "text" field. It is called by the builders before save.
	textmessage.TextValidator = textmessageDescText.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	videomessageFields := schema.VideoMessage{}.Fields()
	_ = videomessageFields
	// videomessageDescMsgId is the schema descriptor for msgId field.
	videomessageDescMsgId := videomessageFields[0].Descriptor()
	// videomessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	videomessage.MsgIdValidator = videomessageDescMsgId.Validators[0].(func(string) error)
	// videomessageDescVideoUrl is the schema descriptor for videoUrl field.
	videomessageDescVideoUrl := videomessageFields[1].Descriptor()
	// videomessage.VideoUrlValidator is a validator for the "videoUrl" field. It is called by the builders before save.
	videomessage.VideoUrlValidator = videomessageDescVideoUrl.Validators[0].(func(string) error)
}
