// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gochat_server/ent/chatrecord"
	"gochat_server/ent/donotdisturb"
	"gochat_server/ent/friendrequest"
	"gochat_server/ent/group"
	"gochat_server/ent/groupchatrecord"
	"gochat_server/ent/imagemessage"
	"gochat_server/ent/message"
	"gochat_server/ent/messagestatus"
	"gochat_server/ent/schema"
	"gochat_server/ent/textmessage"
	"gochat_server/ent/user"
	"gochat_server/ent/videomessage"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatrecordFields := schema.ChatRecord{}.Fields()
	_ = chatrecordFields
	// chatrecordDescMsgId is the schema descriptor for msgId field.
	chatrecordDescMsgId := chatrecordFields[0].Descriptor()
	// chatrecord.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	chatrecord.MsgIdValidator = chatrecordDescMsgId.Validators[0].(func(string) error)
	// chatrecordDescIsGroup is the schema descriptor for isGroup field.
	chatrecordDescIsGroup := chatrecordFields[4].Descriptor()
	// chatrecord.DefaultIsGroup holds the default value on creation for the isGroup field.
	chatrecord.DefaultIsGroup = chatrecordDescIsGroup.Default.(bool)
	// chatrecordDescCreateTime is the schema descriptor for createTime field.
	chatrecordDescCreateTime := chatrecordFields[6].Descriptor()
	// chatrecord.DefaultCreateTime holds the default value on creation for the createTime field.
	chatrecord.DefaultCreateTime = chatrecordDescCreateTime.Default.(func() time.Time)
	donotdisturbFields := schema.DoNotDisturb{}.Fields()
	_ = donotdisturbFields
	// donotdisturbDescUserID is the schema descriptor for user_id field.
	donotdisturbDescUserID := donotdisturbFields[1].Descriptor()
	// donotdisturb.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	donotdisturb.UserIDValidator = donotdisturbDescUserID.Validators[0].(func(int) error)
	// donotdisturbDescIsGlobal is the schema descriptor for is_global field.
	donotdisturbDescIsGlobal := donotdisturbFields[4].Descriptor()
	// donotdisturb.DefaultIsGlobal holds the default value on creation for the is_global field.
	donotdisturb.DefaultIsGlobal = donotdisturbDescIsGlobal.Default.(bool)
	// donotdisturbDescCreatedAt is the schema descriptor for created_at field.
	donotdisturbDescCreatedAt := donotdisturbFields[7].Descriptor()
	// donotdisturb.DefaultCreatedAt holds the default value on creation for the created_at field.
	donotdisturb.DefaultCreatedAt = donotdisturbDescCreatedAt.Default.(func() time.Time)
	// donotdisturbDescUpdatedAt is the schema descriptor for updated_at field.
	donotdisturbDescUpdatedAt := donotdisturbFields[8].Descriptor()
	// donotdisturb.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	donotdisturb.DefaultUpdatedAt = donotdisturbDescUpdatedAt.Default.(func() time.Time)
	// donotdisturb.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	donotdisturb.UpdateDefaultUpdatedAt = donotdisturbDescUpdatedAt.UpdateDefault.(func() time.Time)
	// donotdisturbDescID is the schema descriptor for id field.
	donotdisturbDescID := donotdisturbFields[0].Descriptor()
	// donotdisturb.IDValidator is a validator for the "id" field. It is called by the builders before save.
	donotdisturb.IDValidator = donotdisturbDescID.Validators[0].(func(int) error)
	friendrequestFields := schema.FriendRequest{}.Fields()
	_ = friendrequestFields
	// friendrequestDescStatus is the schema descriptor for status field.
	friendrequestDescStatus := friendrequestFields[3].Descriptor()
	// friendrequest.DefaultStatus holds the default value on creation for the status field.
	friendrequest.DefaultStatus = friendrequestDescStatus.Default.(int)
	// friendrequestDescCreateTime is the schema descriptor for createTime field.
	friendrequestDescCreateTime := friendrequestFields[4].Descriptor()
	// friendrequest.DefaultCreateTime holds the default value on creation for the createTime field.
	friendrequest.DefaultCreateTime = friendrequestDescCreateTime.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescGroupId is the schema descriptor for groupId field.
	groupDescGroupId := groupFields[0].Descriptor()
	// group.GroupIdValidator is a validator for the "groupId" field. It is called by the builders before save.
	group.GroupIdValidator = groupDescGroupId.Validators[0].(func(string) error)
	// groupDescGroupName is the schema descriptor for groupName field.
	groupDescGroupName := groupFields[1].Descriptor()
	// group.GroupNameValidator is a validator for the "groupName" field. It is called by the builders before save.
	group.GroupNameValidator = groupDescGroupName.Validators[0].(func(string) error)
	// groupDescCreateTime is the schema descriptor for createTime field.
	groupDescCreateTime := groupFields[4].Descriptor()
	// group.DefaultCreateTime holds the default value on creation for the createTime field.
	group.DefaultCreateTime = groupDescCreateTime.Default.(func() time.Time)
	groupchatrecordFields := schema.GroupChatRecord{}.Fields()
	_ = groupchatrecordFields
	// groupchatrecordDescMsgId is the schema descriptor for msgId field.
	groupchatrecordDescMsgId := groupchatrecordFields[0].Descriptor()
	// groupchatrecord.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	groupchatrecord.MsgIdValidator = groupchatrecordDescMsgId.Validators[0].(func(string) error)
	// groupchatrecordDescFromUserId is the schema descriptor for fromUserId field.
	groupchatrecordDescFromUserId := groupchatrecordFields[1].Descriptor()
	// groupchatrecord.FromUserIdValidator is a validator for the "fromUserId" field. It is called by the builders before save.
	groupchatrecord.FromUserIdValidator = groupchatrecordDescFromUserId.Validators[0].(func(string) error)
	// groupchatrecordDescGroupId is the schema descriptor for groupId field.
	groupchatrecordDescGroupId := groupchatrecordFields[2].Descriptor()
	// groupchatrecord.GroupIdValidator is a validator for the "groupId" field. It is called by the builders before save.
	groupchatrecord.GroupIdValidator = groupchatrecordDescGroupId.Validators[0].(func(string) error)
	// groupchatrecordDescMsgType is the schema descriptor for msgType field.
	groupchatrecordDescMsgType := groupchatrecordFields[3].Descriptor()
	// groupchatrecord.MsgTypeValidator is a validator for the "msgType" field. It is called by the builders before save.
	groupchatrecord.MsgTypeValidator = groupchatrecordDescMsgType.Validators[0].(func(string) error)
	// groupchatrecordDescCreateTime is the schema descriptor for createTime field.
	groupchatrecordDescCreateTime := groupchatrecordFields[4].Descriptor()
	// groupchatrecord.DefaultCreateTime holds the default value on creation for the createTime field.
	groupchatrecord.DefaultCreateTime = groupchatrecordDescCreateTime.Default.(func() time.Time)
	imagemessageFields := schema.ImageMessage{}.Fields()
	_ = imagemessageFields
	// imagemessageDescMsgId is the schema descriptor for msgId field.
	imagemessageDescMsgId := imagemessageFields[0].Descriptor()
	// imagemessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	imagemessage.MsgIdValidator = imagemessageDescMsgId.Validators[0].(func(string) error)
	// imagemessageDescImageUrl is the schema descriptor for imageUrl field.
	imagemessageDescImageUrl := imagemessageFields[1].Descriptor()
	// imagemessage.ImageUrlValidator is a validator for the "imageUrl" field. It is called by the builders before save.
	imagemessage.ImageUrlValidator = imagemessageDescImageUrl.Validators[0].(func(string) error)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescMsgId is the schema descriptor for msgId field.
	messageDescMsgId := messageFields[0].Descriptor()
	// message.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	message.MsgIdValidator = messageDescMsgId.Validators[0].(func(string) error)
	// messageDescMsgType is the schema descriptor for msgType field.
	messageDescMsgType := messageFields[1].Descriptor()
	// message.MsgTypeValidator is a validator for the "msgType" field. It is called by the builders before save.
	message.MsgTypeValidator = messageDescMsgType.Validators[0].(func(string) error)
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[2].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescIsRevoked is the schema descriptor for isRevoked field.
	messageDescIsRevoked := messageFields[3].Descriptor()
	// message.DefaultIsRevoked holds the default value on creation for the isRevoked field.
	message.DefaultIsRevoked = messageDescIsRevoked.Default.(bool)
	// messageDescCreateTime is the schema descriptor for createTime field.
	messageDescCreateTime := messageFields[5].Descriptor()
	// message.DefaultCreateTime holds the default value on creation for the createTime field.
	message.DefaultCreateTime = messageDescCreateTime.Default.(func() time.Time)
	messagestatusFields := schema.MessageStatus{}.Fields()
	_ = messagestatusFields
	// messagestatusDescMsgId is the schema descriptor for msgId field.
	messagestatusDescMsgId := messagestatusFields[0].Descriptor()
	// messagestatus.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	messagestatus.MsgIdValidator = messagestatusDescMsgId.Validators[0].(func(string) error)
	// messagestatusDescIsDelivered is the schema descriptor for isDelivered field.
	messagestatusDescIsDelivered := messagestatusFields[2].Descriptor()
	// messagestatus.DefaultIsDelivered holds the default value on creation for the isDelivered field.
	messagestatus.DefaultIsDelivered = messagestatusDescIsDelivered.Default.(bool)
	// messagestatusDescIsRead is the schema descriptor for isRead field.
	messagestatusDescIsRead := messagestatusFields[3].Descriptor()
	// messagestatus.DefaultIsRead holds the default value on creation for the isRead field.
	messagestatus.DefaultIsRead = messagestatusDescIsRead.Default.(bool)
	// messagestatusDescCreateTime is the schema descriptor for createTime field.
	messagestatusDescCreateTime := messagestatusFields[6].Descriptor()
	// messagestatus.DefaultCreateTime holds the default value on creation for the createTime field.
	messagestatus.DefaultCreateTime = messagestatusDescCreateTime.Default.(func() time.Time)
	textmessageFields := schema.TextMessage{}.Fields()
	_ = textmessageFields
	// textmessageDescMsgId is the schema descriptor for msgId field.
	textmessageDescMsgId := textmessageFields[0].Descriptor()
	// textmessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	textmessage.MsgIdValidator = textmessageDescMsgId.Validators[0].(func(string) error)
	// textmessageDescText is the schema descriptor for text field.
	textmessageDescText := textmessageFields[1].Descriptor()
	// textmessage.TextValidator is a validator for the "text" field. It is called by the builders before save.
	textmessage.TextValidator = textmessageDescText.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[9].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	videomessageFields := schema.VideoMessage{}.Fields()
	_ = videomessageFields
	// videomessageDescMsgId is the schema descriptor for msgId field.
	videomessageDescMsgId := videomessageFields[0].Descriptor()
	// videomessage.MsgIdValidator is a validator for the "msgId" field. It is called by the builders before save.
	videomessage.MsgIdValidator = videomessageDescMsgId.Validators[0].(func(string) error)
	// videomessageDescVideoUrl is the schema descriptor for videoUrl field.
	videomessageDescVideoUrl := videomessageFields[1].Descriptor()
	// videomessage.VideoUrlValidator is a validator for the "videoUrl" field. It is called by the builders before save.
	videomessage.VideoUrlValidator = videomessageDescVideoUrl.Validators[0].(func(string) error)
}
