// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gochat_server/ent/predicate"
	"gochat_server/ent/textmessage"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TextMessageDelete is the builder for deleting a TextMessage entity.
type TextMessageDelete struct {
	config
	hooks    []Hook
	mutation *TextMessageMutation
}

// Where appends a list predicates to the TextMessageDelete builder.
func (tmd *TextMessageDelete) Where(ps ...predicate.TextMessage) *TextMessageDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TextMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tmd.sqlExec, tmd.mutation, tmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TextMessageDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TextMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(textmessage.Table, sqlgraph.NewFieldSpec(textmessage.FieldID, field.TypeInt))
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tmd.mutation.done = true
	return affected, err
}

// TextMessageDeleteOne is the builder for deleting a single TextMessage entity.
type TextMessageDeleteOne struct {
	tmd *TextMessageDelete
}

// Where appends a list predicates to the TextMessageDelete builder.
func (tmdo *TextMessageDeleteOne) Where(ps ...predicate.TextMessage) *TextMessageDeleteOne {
	tmdo.tmd.mutation.Where(ps...)
	return tmdo
}

// Exec executes the deletion query.
func (tmdo *TextMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{textmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TextMessageDeleteOne) ExecX(ctx context.Context) {
	if err := tmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
