// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gochat_server/ent/predicate"
	"gochat_server/ent/textmessage"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TextMessageQuery is the builder for querying TextMessage entities.
type TextMessageQuery struct {
	config
	ctx        *QueryContext
	order      []textmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.TextMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TextMessageQuery builder.
func (tmq *TextMessageQuery) Where(ps ...predicate.TextMessage) *TextMessageQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit the number of records to be returned by this query.
func (tmq *TextMessageQuery) Limit(limit int) *TextMessageQuery {
	tmq.ctx.Limit = &limit
	return tmq
}

// Offset to start from.
func (tmq *TextMessageQuery) Offset(offset int) *TextMessageQuery {
	tmq.ctx.Offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TextMessageQuery) Unique(unique bool) *TextMessageQuery {
	tmq.ctx.Unique = &unique
	return tmq
}

// Order specifies how the records should be ordered.
func (tmq *TextMessageQuery) Order(o ...textmessage.OrderOption) *TextMessageQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// First returns the first TextMessage entity from the query.
// Returns a *NotFoundError when no TextMessage was found.
func (tmq *TextMessageQuery) First(ctx context.Context) (*TextMessage, error) {
	nodes, err := tmq.Limit(1).All(setContextOp(ctx, tmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{textmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TextMessageQuery) FirstX(ctx context.Context) *TextMessage {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TextMessage ID from the query.
// Returns a *NotFoundError when no TextMessage ID was found.
func (tmq *TextMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(1).IDs(setContextOp(ctx, tmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{textmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TextMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TextMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TextMessage entity is found.
// Returns a *NotFoundError when no TextMessage entities are found.
func (tmq *TextMessageQuery) Only(ctx context.Context) (*TextMessage, error) {
	nodes, err := tmq.Limit(2).All(setContextOp(ctx, tmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{textmessage.Label}
	default:
		return nil, &NotSingularError{textmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TextMessageQuery) OnlyX(ctx context.Context) *TextMessage {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TextMessage ID in the query.
// Returns a *NotSingularError when more than one TextMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TextMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(2).IDs(setContextOp(ctx, tmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{textmessage.Label}
	default:
		err = &NotSingularError{textmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TextMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TextMessages.
func (tmq *TextMessageQuery) All(ctx context.Context) ([]*TextMessage, error) {
	ctx = setContextOp(ctx, tmq.ctx, ent.OpQueryAll)
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TextMessage, *TextMessageQuery]()
	return withInterceptors[[]*TextMessage](ctx, tmq, qr, tmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TextMessageQuery) AllX(ctx context.Context) []*TextMessage {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TextMessage IDs.
func (tmq *TextMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tmq.ctx.Unique == nil && tmq.path != nil {
		tmq.Unique(true)
	}
	ctx = setContextOp(ctx, tmq.ctx, ent.OpQueryIDs)
	if err = tmq.Select(textmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TextMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TextMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tmq.ctx, ent.OpQueryCount)
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tmq, querierCount[*TextMessageQuery](), tmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TextMessageQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TextMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tmq.ctx, ent.OpQueryExist)
	switch _, err := tmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TextMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TextMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TextMessageQuery) Clone() *TextMessageQuery {
	if tmq == nil {
		return nil
	}
	return &TextMessageQuery{
		config:     tmq.config,
		ctx:        tmq.ctx.Clone(),
		order:      append([]textmessage.OrderOption{}, tmq.order...),
		inters:     append([]Interceptor{}, tmq.inters...),
		predicates: append([]predicate.TextMessage{}, tmq.predicates...),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TextMessage.Query().
//		GroupBy(textmessage.FieldMsgId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tmq *TextMessageQuery) GroupBy(field string, fields ...string) *TextMessageGroupBy {
	tmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TextMessageGroupBy{build: tmq}
	grbuild.flds = &tmq.ctx.Fields
	grbuild.label = textmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MsgId string `json:"msgId,omitempty"`
//	}
//
//	client.TextMessage.Query().
//		Select(textmessage.FieldMsgId).
//		Scan(ctx, &v)
func (tmq *TextMessageQuery) Select(fields ...string) *TextMessageSelect {
	tmq.ctx.Fields = append(tmq.ctx.Fields, fields...)
	sbuild := &TextMessageSelect{TextMessageQuery: tmq}
	sbuild.label = textmessage.Label
	sbuild.flds, sbuild.scan = &tmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TextMessageSelect configured with the given aggregations.
func (tmq *TextMessageQuery) Aggregate(fns ...AggregateFunc) *TextMessageSelect {
	return tmq.Select().Aggregate(fns...)
}

func (tmq *TextMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tmq); err != nil {
				return err
			}
		}
	}
	for _, f := range tmq.ctx.Fields {
		if !textmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TextMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TextMessage, error) {
	var (
		nodes = []*TextMessage{}
		_spec = tmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TextMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TextMessage{config: tmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tmq *TextMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.ctx.Fields
	if len(tmq.ctx.Fields) > 0 {
		_spec.Unique = tmq.ctx.Unique != nil && *tmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TextMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(textmessage.Table, textmessage.Columns, sqlgraph.NewFieldSpec(textmessage.FieldID, field.TypeInt))
	_spec.From = tmq.sql
	if unique := tmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tmq.path != nil {
		_spec.Unique = true
	}
	if fields := tmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, textmessage.FieldID)
		for i := range fields {
			if fields[i] != textmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TextMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(textmessage.Table)
	columns := tmq.ctx.Fields
	if len(columns) == 0 {
		columns = textmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.ctx.Unique != nil && *tmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TextMessageGroupBy is the group-by builder for TextMessage entities.
type TextMessageGroupBy struct {
	selector
	build *TextMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TextMessageGroupBy) Aggregate(fns ...AggregateFunc) *TextMessageGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the selector query and scans the result into the given value.
func (tmgb *TextMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tmgb.build.ctx, ent.OpQueryGroupBy)
	if err := tmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TextMessageQuery, *TextMessageGroupBy](ctx, tmgb.build, tmgb, tmgb.build.inters, v)
}

func (tmgb *TextMessageGroupBy) sqlScan(ctx context.Context, root *TextMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tmgb.flds)+len(tmgb.fns))
		for _, f := range *tmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TextMessageSelect is the builder for selecting fields of TextMessage entities.
type TextMessageSelect struct {
	*TextMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tms *TextMessageSelect) Aggregate(fns ...AggregateFunc) *TextMessageSelect {
	tms.fns = append(tms.fns, fns...)
	return tms
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TextMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tms.ctx, ent.OpQuerySelect)
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TextMessageQuery, *TextMessageSelect](ctx, tms.TextMessageQuery, tms, tms.inters, v)
}

func (tms *TextMessageSelect) sqlScan(ctx context.Context, root *TextMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tms.fns))
	for _, fn := range tms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
