// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gochat_server/ent/textmessage"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TextMessage is the model entity for the TextMessage schema.
type TextMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 消息ID,由发送者产生
	MsgId string `json:"msgId,omitempty"`
	// 文本消息
	Text         string `json:"text,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TextMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case textmessage.FieldID:
			values[i] = new(sql.NullInt64)
		case textmessage.FieldMsgId, textmessage.FieldText:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TextMessage fields.
func (tm *TextMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case textmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tm.ID = int(value.Int64)
		case textmessage.FieldMsgId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field msgId", values[i])
			} else if value.Valid {
				tm.MsgId = value.String
			}
		case textmessage.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				tm.Text = value.String
			}
		default:
			tm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TextMessage.
// This includes values selected through modifiers, order, etc.
func (tm *TextMessage) Value(name string) (ent.Value, error) {
	return tm.selectValues.Get(name)
}

// Update returns a builder for updating this TextMessage.
// Note that you need to call TextMessage.Unwrap() before calling this method if this TextMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (tm *TextMessage) Update() *TextMessageUpdateOne {
	return NewTextMessageClient(tm.config).UpdateOne(tm)
}

// Unwrap unwraps the TextMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tm *TextMessage) Unwrap() *TextMessage {
	_tx, ok := tm.config.driver.(*txDriver)
	if !ok {
		panic("ent: TextMessage is not a transactional entity")
	}
	tm.config.driver = _tx.drv
	return tm
}

// String implements the fmt.Stringer.
func (tm *TextMessage) String() string {
	var builder strings.Builder
	builder.WriteString("TextMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tm.ID))
	builder.WriteString("msgId=")
	builder.WriteString(tm.MsgId)
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(tm.Text)
	builder.WriteByte(')')
	return builder.String()
}

// TextMessages is a parsable slice of TextMessage.
type TextMessages []*TextMessage
